### ISSUE TITLE
Median read length values need to be integer in rare cases?

### ISSUE THREAD

**Issue by yoshihikosuzuki** [juniper-lake/CoLoRSdb#67]
Hi Juniper,

Thanks for your great efforts in making this pipeline.

I think I found a bug happening in rare cases while calculating read stats in the pbmm2 task. I came across this in the workflow of commit ID 4ea98f1, but it looks it still remains.
Specifically, when a median read length value becomes (not an integer but) a float value, the subsequent process raises an error. I propose the following modification of a single line of running awk:

```
diff --git a/wdl/tasks/pbmm2.wdl b/wdl/tasks/pbmm2.wdl
index 4fcbf68..bb760d4 100644
--- a/wdl/tasks/pbmm2.wdl
+++ b/wdl/tasks/pbmm2.wdl
@@ -77,7 +77,7 @@ task combine_smrtcell_stats {
 
     cat ~{sep=' ' read_length_and_quality_tsvs} \
       | datamash count 1 countunique 1 median 2 mean 2 pstdev 2 median 3 mean 3 pstdev 3 \
-      | awk '{OFS="\n"; $1=$1}1' \
+      | awk '{OFS="\n"; $3=int($3); $6=int($6)}1' \
       > ~{sample_id}.smrtcell_stats.txt
 
     sed '1q;d' ~{sample_id}.smrtcell_stats.txt > read_count.txt
```

Best regards,
Yoshi

**Comment by juniper-lake** [comment]
Thanks for the bug info! Fixed a different way by changing the WDL data type in outputs/inputs instead of modifying the task command

**Comment by yoshihikosuzuki** [comment]
Thanks for your quick response!
Just one thing: doesn't the RHS need to be `read_float` instead of `read_int`?

```
    Float read_length_median = read_int("read_length_median.txt")
```

**Comment by juniper-lake** [comment]
Fixed. Thanks for your help!
